$ErrorActionPreference='Stop';$product=Get-CimInstance Win32_ComputerSystemProduct
if($env:COMPUTERNAME -cne 'DESKTOP-O1LP5DG' -or $product.UUID -cne 'C6440689-D11C-4C63-A463-F3722B7DDB69'){throw 'Builder identity mismatch.'}
$thumb='220DD82C37FCF36048D59E4F10113185D81D5DC7';$cert=Get-Item -LiteralPath ('Cert:\CurrentUser\My\'+$thumb)
$public=[System.Security.Cryptography.X509Certificates.RSACertificateExtensions]::GetRSAPublicKey($cert).ExportParameters($false)
$expectedMod=[Convert]::ToBase64String($public.Modulus);$expectedExp=[Convert]::ToBase64String($public.Exponent);$rows=@()
$kspNames=@('{7CA57DD6-6AD2-49F4-9D32-0FEC6F504D6D}','{7FA1DF32-E0F3-4734-962C-CB989632BE2D}','te-2c0d0888-dbd0-4831-acb8-bad61a912506','Microsoft Connected Devices Platform device certificate','{ED15F7E8-49BE-4066-B5AD-37F79E44FAFC}')
foreach($name in $kspNames){$row=[ordered]@{Provider='Microsoft Software Key Storage Provider';Container=$name;Opened=$false;PublicKeyCompared=$false;ExactPublicMatch=$false;KeySize=$null;Error=$null};try{$key=[System.Security.Cryptography.CngKey]::Open($name,[System.Security.Cryptography.CngProvider]::MicrosoftSoftwareKeyStorageProvider,[System.Security.Cryptography.CngKeyOpenOptions]::UserKey);$rsa=[System.Security.Cryptography.RSACng]::new($key);$actual=$rsa.ExportParameters($false);$row.Opened=$true;$row.PublicKeyCompared=$true;$row.ExactPublicMatch=([Convert]::ToBase64String($actual.Modulus) -ceq $expectedMod -and [Convert]::ToBase64String($actual.Exponent) -ceq $expectedExp);$row.KeySize=$rsa.KeySize;$rsa.Dispose();$key.Dispose()}catch{$row.Error=$_.Exception.ToString()};$rows += $row}
$csps=@(@{Name='Microsoft Base Cryptographic Provider v1.0';Type=1},@{Name='Microsoft Enhanced Cryptographic Provider v1.0';Type=1},@{Name='Microsoft Enhanced RSA and AES Cryptographic Provider';Type=24},@{Name='Microsoft RSA SChannel Cryptographic Provider';Type=12},@{Name='Microsoft Strong Cryptographic Provider';Type=1})
foreach($provider in $csps){foreach($keyNumber in @(1,2)){$row=[ordered]@{Provider=$provider.Name;Container='J2SE';KeyNumber=$keyNumber;Opened=$false;PublicKeyCompared=$false;ExactPublicMatch=$false;KeySize=$null;Error=$null};try{$cp=New-Object System.Security.Cryptography.CspParameters;$cp.ProviderName=$provider.Name;$cp.ProviderType=$provider.Type;$cp.KeyContainerName='J2SE';$cp.KeyNumber=$keyNumber;$cp.Flags=[System.Security.Cryptography.CspProviderFlags]::UseExistingKey -bor [System.Security.Cryptography.CspProviderFlags]::NoPrompt;$rsa=[System.Security.Cryptography.RSACryptoServiceProvider]::new(0,$cp);$actual=$rsa.ExportParameters($false);$row.Opened=$true;$row.PublicKeyCompared=$true;$row.ExactPublicMatch=([Convert]::ToBase64String($actual.Modulus) -ceq $expectedMod -and [Convert]::ToBase64String($actual.Exponent) -ceq $expectedExp);$row.KeySize=$rsa.KeySize;$rsa.Dispose()}catch{$row.Error=$_.Exception.ToString()};$rows += $row}}
[ordered]@{Status='Completed';UTC=[DateTime]::UtcNow.ToString('o');ComputerName=$env:COMPUTERNAME;UUID=$product.UUID;User=[Security.Principal.WindowsIdentity]::GetCurrent().Name;CertThumbprint=$cert.Thumbprint;CertPublicKeyComparedByExactModulusAndExponent=$true;PrivateMaterialReadOrExported=$false;Candidates=$rows}|ConvertTo-Json -Depth 16 -Compress
