$ErrorActionPreference='Stop'
$expectedComputer='DESKTOP-O1LP5DG';$expectedUuid='C6440689-D11C-4C63-A463-F3722B7DDB69';$thumb='220DD82C37FCF36048D59E4F10113185D81D5DC7'
$product=Get-CimInstance Win32_ComputerSystemProduct
if($env:COMPUTERNAME -cne $expectedComputer -or $product.UUID -cne $expectedUuid){throw 'Builder identity mismatch.'}
$roots=@('C:\safeupload-cert','C:\safeupload','C:\safeupload-pkg','C:\ProgramData\SafeUpload','C:\Users\vika\Desktop','C:\Users\vika\Downloads','C:\Users\vika\Documents','C:\Users\vika\OneDrive')
$files=@();foreach($root in $roots){if(Test-Path -LiteralPath $root){$files+=@(Get-ChildItem -LiteralPath $root -File -Force -Recurse -ErrorAction SilentlyContinue|Where-Object {$_.Extension -match '^\.(pfx|p12|pvk|key|cer|crt)$'})}}
$files=@($files|Sort-Object -Property FullName -Unique);$candidateRows=@()
foreach($file in $files){$row=[ordered]@{Path=$file.FullName;Extension=$file.Extension;Length=$file.Length;CreationUtc=$file.CreationTimeUtc.ToString('o');LastWriteUtc=$file.LastWriteTimeUtc.ToString('o');SHA256=(Get-FileHash -LiteralPath $file.FullName -Algorithm SHA256).Hash;CertificateThumbprint=$null;ExactThumbprintMatch=$null;PrivateMaterialDecodedOrImported=$false};if($file.Extension -match '^\.(cer|crt)$'){try{$cert=[System.Security.Cryptography.X509Certificates.X509Certificate2]::new($file.FullName);$row.CertificateThumbprint=$cert.Thumbprint;$row.ExactThumbprintMatch=($cert.Thumbprint -ceq $thumb)}catch{$row.CertificateThumbprint='Unreadable public certificate metadata'}};$candidateRows+=$row}
$historyFiles=@();$historyPath=Join-Path $env:APPDATA 'Microsoft\Windows\PowerShell\PSReadLine\ConsoleHost_history.txt';if(Test-Path -LiteralPath $historyPath){$historyFiles+=$historyPath};$historyFiles+=@(Get-ChildItem -LiteralPath 'C:\Users\vika\Documents' -Filter 'PowerShell_transcript*.txt' -File -Force -ErrorAction SilentlyContinue|ForEach-Object {$_.FullName})
$providers=@('Microsoft Software Key Storage Provider','Microsoft Base Cryptographic Provider v1.0','Microsoft Enhanced Cryptographic Provider v1.0','Microsoft Enhanced RSA and AES Cryptographic Provider','Microsoft RSA SChannel Cryptographic Provider','Microsoft Strong Cryptographic Provider');$historyRows=@()
foreach($path in $historyFiles){$lines=Get-Content -LiteralPath $path -ErrorAction SilentlyContinue;$pathRefs=@();$providerRefs=@();$matchedCount=0;foreach($line in $lines){if($line -match '(?i)(safeupload|\.pfx|\.p12|\.pvk|certutil|certreq|import-pfx|export-pfx|new-selfsignedcertificate|key container|keyset)'){$matchedCount++;foreach($m in [regex]::Matches($line,'(?i)[a-z]:\\[^"''\s,;<>|]+\.(?:pfx|p12|pvk|cer|crt|key)')){$pathRefs+=$m.Value};foreach($provider in $providers){if($line.Contains($provider)){$providerRefs+=$provider}}}};$historyRows+=[ordered]@{HistoryPath=$path;MatchedLineCount=$matchedCount;CertificateOrKeyFilePathReferences=@($pathRefs|Sort-Object -Unique);ProviderReferences=@($providerRefs|Sort-Object -Unique);RawHistoryLinesEmitted=$false;PasswordOrKeyMaterialEmitted=$false}}
[ordered]@{Status='Completed';UTC=[DateTime]::UtcNow.ToString('o');ComputerName=$env:COMPUTERNAME;UUID=$product.UUID;User=[Security.Principal.WindowsIdentity]::GetCurrent().Name;SearchRoots=$roots;CandidateFiles=$candidateRows;HistoryMetadata=$historyRows;PfxDecodedOrImported=$false;PrivateKeyMaterialExported=$false}|ConvertTo-Json -Depth 12 -Compress
