spring.application.name=safeupload-backend

server.port=4200
server.address=${SAFEUPLOAD_BIND_ADDRESS:127.0.0.1}

app.datasource.url=jdbc:mysql://localhost:3306/app
app.datasource.username=ms_safeupload
app.datasource.password=admin123
app.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

acesso.datasource.url=jdbc:mysql://localhost:3306/acesso
acesso.datasource.username=ms_safeupload
acesso.datasource.password=admin123
acesso.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.jpa.hibernate.ddl-auto=validate

server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=lax

spring.jackson.deserialization.fail-on-numbers-for-enums=true

spring.h2.console.enabled=false