$ErrorActionPreference='Stop'
$expectedComputer='DESKTOP-O1LP5DG';$expectedUuid='C6440689-D11C-4C63-A463-F3722B7DDB69';$thumb='220DD82C37FCF36048D59E4F10113185D81D5DC7'
$product=Get-CimInstance Win32_ComputerSystemProduct
if($env:COMPUTERNAME -cne $expectedComputer -or $product.UUID -cne $expectedUuid){throw 'Builder identity mismatch.'}
$identity=[Security.Principal.WindowsIdentity]::GetCurrent();$sid=$identity.User.Value
$profile=Get-CimInstance Win32_UserProfile -Filter "SID='$sid'" -ErrorAction SilentlyContinue
$proc=Get-CimInstance Win32_Process -Filter "ProcessId=$PID" -ErrorAction SilentlyContinue
$cryptoRoots=@((Join-Path $env:APPDATA 'Microsoft\Crypto\Keys'),(Join-Path $env:APPDATA 'Microsoft\Crypto\RSA'));$keyFiles=@()
foreach($root in $cryptoRoots){if(Test-Path -LiteralPath $root){foreach($f in Get-ChildItem -LiteralPath $root -File -Force -ErrorAction SilentlyContinue){$keyFiles+=[ordered]@{Directory=$root;Name=$f.Name;Length=$f.Length;CreationUtc=$f.CreationTimeUtc.ToString('o');LastWriteUtc=$f.LastWriteTimeUtc.ToString('o');Attributes=$f.Attributes.ToString();ContentsRead=$false}}}}
$sessions=@();$ownedCounts=@{};foreach($p in Get-CimInstance Win32_Process -ErrorAction SilentlyContinue){try{$owner=Invoke-CimMethod -InputObject $p -MethodName GetOwnerSid -ErrorAction Stop;if($owner.Sid -ceq $sid){$k=[string]$p.SessionId;if(-not $ownedCounts.ContainsKey($k)){$ownedCounts[$k]=0};$ownedCounts[$k]++}}catch{}};foreach($k in $ownedCounts.Keys){$sessions+=[ordered]@{SessionId=[int]$k;OwnedProcessCount=$ownedCounts[$k];Source='Win32_Process owner SID'}}
$quserPath=Join-Path $env:windir 'System32\quser.exe';$quserExit=$null;$quserUserRows=@();if(Test-Path -LiteralPath $quserPath){$out=Join-Path $env:TEMP ('safeupload-quser-'+[Guid]::NewGuid().ToString('N')+'.out');$err=Join-Path $env:TEMP ('safeupload-quser-'+[Guid]::NewGuid().ToString('N')+'.err');try{$q=Start-Process -FilePath $quserPath -NoNewWindow -Wait -PassThru -RedirectStandardOutput $out -RedirectStandardError $err;$quserExit=$q.ExitCode;if(Test-Path -LiteralPath $out){$quserUserRows=@(Get-Content -LiteralPath $out|Where-Object {$_ -match '(?i)(^|\s)vika(\s|$)'})|ForEach-Object {$_.Trim()}}}finally{Remove-Item -LiteralPath $out,$err -Force -ErrorAction SilentlyContinue}}
$cert=Get-Item -LiteralPath ('Cert:\CurrentUser\My\'+$thumb)
[ordered]@{Status='Completed';UTC=[DateTime]::UtcNow.ToString('o');ComputerName=$env:COMPUTERNAME;UUID=$product.UUID;Identity=$identity.Name;SID=$sid;UserProfile=[ordered]@{EnvironmentProfile=$env:USERPROFILE;CimLocalPath=$profile.LocalPath;Loaded=[bool]$profile.Loaded;Special=[bool]$profile.Special;RegistryHiveLoaded=(Test-Path -LiteralPath ('Registry::HKEY_USERS\'+$sid))};CurrentProcess=[ordered]@{PID=$PID;SessionId=$proc.SessionId;Name=$proc.Name};VikaSessionProcessCounts=$sessions;QuserExitCode=$quserExit;QuserRowsForVikaOnly=$quserUserRows;CryptoKeyDirectories=$cryptoRoots;CryptoKeyFiles=$keyFiles;Certificate=[ordered]@{Thumbprint=$cert.Thumbprint;HasPrivateKey=[bool]$cert.HasPrivateKey;CertificatePrivateKeyOpened=$false;KeyFileContentsRead=$false}}|ConvertTo-Json -Depth 10 -Compress
