$ErrorActionPreference='Stop'
$expectedComputer='DESKTOP-O1LP5DG';$expectedUuid='C6440689-D11C-4C63-A463-F3722B7DDB69';$expectedSid='S-1-5-21-316478115-1595729549-2803163825-1001';$thumb='220DD82C37FCF36048D59E4F10113185D81D5DC7'
$publicCer='C:\safeupload-cert\SafeUploadTest.cer';$publicCerHash='46E4E8082155E2EE9E3602C613224322F863ADB85EC02C542FF2F4C8700BA0A1'
$product=Get-CimInstance Win32_ComputerSystemProduct;$identity=[Security.Principal.WindowsIdentity]::GetCurrent();$process=Get-CimInstance Win32_Process -Filter "ProcessId=$PID"
if($env:COMPUTERNAME -cne $expectedComputer -or $product.UUID -cne $expectedUuid){throw 'Builder identity mismatch.'}
if($identity.User.Value -cne $expectedSid -or $identity.Name -cne 'DESKTOP-O1LP5DG\vika'){throw 'Expected vika identity mismatch.'}
if([int]$process.SessionId -le 0){throw 'InteractiveToken session required; no key operation attempted.'}
if((Get-FileHash -LiteralPath $publicCer -Algorithm SHA256).Hash -cne $publicCerHash){throw 'Pinned public certificate hash mismatch.'}
$cert=Get-Item -LiteralPath ('Cert:\CurrentUser\My\'+$thumb);$public=[System.Security.Cryptography.X509Certificates.X509Certificate2]::new($publicCer)
if(-not $cert.HasPrivateKey -or $cert.Thumbprint -cne $thumb -or $public.Thumbprint -cne $thumb){throw 'Expected existing certificate identity mismatch.'}
$expected=[System.Security.Cryptography.X509Certificates.RSACertificateExtensions]::GetRSAPublicKey($public).ExportParameters($false);$actual=[System.Security.Cryptography.X509Certificates.RSACertificateExtensions]::GetRSAPublicKey($cert).ExportParameters($false)
if([Convert]::ToBase64String($expected.Modulus) -cne [Convert]::ToBase64String($actual.Modulus) -or [Convert]::ToBase64String($expected.Exponent) -cne [Convert]::ToBase64String($actual.Exponent)){throw 'Stored certificate public RSA mismatch.'}
$rsa=$null;$publicRsa=$null;$challenge=$null;$signature=$null;$result=[ordered]@{Status='Started';UTC=[DateTime]::UtcNow.ToString('o');ComputerName=$env:COMPUTERNAME;UUID=$product.UUID;User=$identity.Name;SID=$identity.User.Value;SessionId=$process.SessionId;CertificateThumbprint=$cert.Thumbprint;HasPrivateKey=$true;PublicRsaMatchesPinnedCer=$true;PrivateKeyOpened=$false;Provider=$null;KeySize=$null;ChallengeSignatureVerified=$false;SignatureBytesEmitted=$false;PrivateKeyMaterialExported=$false;PersistentStateChanged=$false;ErrorType=$null;ErrorHResult=$null}
try{$rsa=[System.Security.Cryptography.X509Certificates.RSACertificateExtensions]::GetRSAPrivateKey($cert);if($null -eq $rsa){throw 'Existing certificate key could not be opened.'};$result.PrivateKeyOpened=$true;$result.KeySize=$rsa.KeySize;if($rsa -is [System.Security.Cryptography.RSACng]){$result.Provider=$rsa.Key.Provider.Provider}elseif($rsa -is [System.Security.Cryptography.RSACryptoServiceProvider]){$result.Provider=$rsa.CspKeyContainerInfo.ProviderName};$challenge=New-Object byte[] 32;[System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($challenge);$publicRsa=[System.Security.Cryptography.X509Certificates.RSACertificateExtensions]::GetRSAPublicKey($public);if($rsa -is [System.Security.Cryptography.RSACng]){$signature=$rsa.SignData($challenge,[System.Security.Cryptography.HashAlgorithmName]::SHA256,[System.Security.Cryptography.RSASignaturePadding]::Pkcs1);$result.ChallengeSignatureVerified=$publicRsa.VerifyData($challenge,$signature,[System.Security.Cryptography.HashAlgorithmName]::SHA256,[System.Security.Cryptography.RSASignaturePadding]::Pkcs1)}elseif($rsa -is [System.Security.Cryptography.RSACryptoServiceProvider]){$oid=[System.Security.Cryptography.CryptoConfig]::MapNameToOID('SHA256');$signature=$rsa.SignData($challenge,$oid);$result.ChallengeSignatureVerified=$publicRsa.VerifyData($challenge,$oid,$signature)}else{throw 'Unsupported existing RSA implementation.'};$result.ChallengeSHA256=[BitConverter]::ToString([System.Security.Cryptography.SHA256]::Create().ComputeHash($challenge)).Replace('-','');$result.Status='Completed'}catch{$result.Status='ProbeFailed';$result.ErrorType=$_.Exception.GetType().FullName;$result.ErrorHResult=('0x{0:X8}' -f $_.Exception.HResult)}finally{if($null -ne $signature){[Array]::Clear($signature,0,$signature.Length)};if($null -ne $challenge){[Array]::Clear($challenge,0,$challenge.Length)};if($null -ne $rsa){$rsa.Dispose()};if($null -ne $publicRsa){$publicRsa.Dispose()};if($null -ne $public){$public.Dispose()}}
$result|ConvertTo-Json -Depth 6 -Compress
